#!/usr/bin/env bash
#
# Initialize a persistent SoftHSM2 token on a self-hosted GitHub Actions runner.
#
# Run this ONCE on the runner host before enabling signing_mode=softhsm.
# The token persists across workflow runs — the same key signs every build.
#
# Usage:
#   sudo ./setup-softhsm-runner.sh [options]
#
# Options:
#   --token-label NAME    Token label (default: trust-lists)
#   --key-label NAME      Signing key label (default: signing-key)
#   --cert-label NAME     Certificate label (default: signing-cert)
#   --key-id HEX          Key/cert ID in hex (default: 01)
#   --key-type TYPE       Key type for pkcs11-tool (default: ec:prime256v1)
#   --cert-subject SUB    Certificate subject (default: /CN=trust.siros.org Trust List Signer)
#   --cert-days N         Certificate validity in days (default: 1095 = 3 years)
#   --token-dir PATH      Token storage directory (default: /var/lib/softhsm/trust-lists)
#   --conf-path PATH      Config file path (default: /etc/softhsm/trust-lists.conf)
#   --runner-user USER    GitHub runner user (default: runner)
#
set -euo pipefail

# ── Defaults ────────────────────────────────────────────────────────
TOKEN_LABEL="trust-lists"
KEY_LABEL="signing-key"
CERT_LABEL="signing-cert"
KEY_ID="01"
KEY_TYPE="ec:prime256v1"
CERT_SUBJECT="/CN=trust.siros.org Trust List Signer"
CERT_DAYS=1095
TOKEN_DIR="/var/lib/softhsm/trust-lists"
CONF_PATH="/etc/softhsm/trust-lists.conf"
RUNNER_USER="runner"

# ── Parse args ──────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --token-label)  TOKEN_LABEL="$2"; shift 2 ;;
    --key-label)    KEY_LABEL="$2"; shift 2 ;;
    --cert-label)   CERT_LABEL="$2"; shift 2 ;;
    --key-id)       KEY_ID="$2"; shift 2 ;;
    --key-type)     KEY_TYPE="$2"; shift 2 ;;
    --cert-subject) CERT_SUBJECT="$2"; shift 2 ;;
    --cert-days)    CERT_DAYS="$2"; shift 2 ;;
    --token-dir)    TOKEN_DIR="$2"; shift 2 ;;
    --conf-path)    CONF_PATH="$2"; shift 2 ;;
    --runner-user)  RUNNER_USER="$2"; shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# ── Preflight checks ───────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root (sudo)." >&2
  exit 1
fi

for cmd in softhsm2-util pkcs11-tool openssl; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "Required command not found: $cmd" >&2
    echo "Install with: apt-get install softhsm2 opensc openssl" >&2
    exit 1
  fi
done

# Find PKCS#11 module
PKCS11_MODULE=""
for p in /usr/lib/softhsm/libsofthsm2.so /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so /usr/lib64/softhsm/libsofthsm2.so /usr/local/lib/softhsm/libsofthsm2.so; do
  if [ -f "$p" ]; then
    PKCS11_MODULE="$p"
    break
  fi
done
if [ -z "$PKCS11_MODULE" ]; then
  echo "Could not find libsofthsm2.so — is softhsm2 installed?" >&2
  exit 1
fi

# ── Create token directory ──────────────────────────────────────────
echo "Creating token directory: $TOKEN_DIR"
mkdir -p "$TOKEN_DIR"
chmod 750 "$TOKEN_DIR"
chown "$RUNNER_USER:$RUNNER_USER" "$TOKEN_DIR"

# ── Write SoftHSM2 config ──────────────────────────────────────────
echo "Writing SoftHSM2 config: $CONF_PATH"
mkdir -p "$(dirname "$CONF_PATH")"
cat > "$CONF_PATH" <<EOF
# SoftHSM2 configuration for trust-lists signing
# Generated by setup-softhsm-runner.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
directories.tokendir = $TOKEN_DIR
objectstore.backend = file
log.level = INFO
slots.removable = true
EOF
chmod 644 "$CONF_PATH"

# ── Initialize token ───────────────────────────────────────────────
echo "Initializing SoftHSM2 token..."
read -rsp "Enter user PIN for the token: " USER_PIN
echo
read -rsp "Enter SO (admin) PIN for the token: " SO_PIN
echo

export SOFTHSM2_CONF="$CONF_PATH"

softhsm2-util --init-token --free \
  --label "$TOKEN_LABEL" \
  --so-pin "$SO_PIN" \
  --pin "$USER_PIN"

# ── Generate signing key in token ──────────────────────────────────
echo "Generating signing key ($KEY_TYPE) in token..."
pkcs11-tool --module "$PKCS11_MODULE" \
  --token-label "$TOKEN_LABEL" \
  --login --pin "$USER_PIN" \
  --keypairgen --key-type "$KEY_TYPE" \
  --id "$KEY_ID" \
  --label "$KEY_LABEL"

# ── Generate and import certificate ─────────────────────────────────
#
# The certificate MUST be issued for the key that was just created in the
# token. Do not reach for "openssl req -x509 -newkey ...": that generates
# its own key pair, so the certificate ends up describing a key the token
# does not hold. Signing then succeeds and produces signatures that nobody
# can verify, with no error at signing time.
#
# tsl-tool -selfsign-cert takes the public key from the token and has the
# token sign, so the two cannot disagree.
echo "Issuing self-signed certificate for the token's key..."
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

if ! command -v tsl-tool &>/dev/null; then
  echo "tsl-tool not found in PATH — required to issue the certificate." >&2
  echo "Install it from https://github.com/sirosfoundation/g119612/releases" >&2
  exit 1
fi

# CERT_SUBJECT is an openssl-style /CN=... string; tsl-tool takes the CN.
CERT_CN="${CERT_SUBJECT#/CN=}"

tsl-tool -selfsign-cert \
  -pkcs11-uri "pkcs11:module=${PKCS11_MODULE};pin=${USER_PIN};token=${TOKEN_LABEL}" \
  -key-label "$KEY_LABEL" \
  -key-id "$KEY_ID" \
  -cert-label "$CERT_LABEL" \
  -subject "$CERT_CN" \
  -days "$CERT_DAYS" \
  -output "$TMPDIR/root-signer.pem"

echo ""
echo "Certificate issued. Commit this as certs/root-signer.pem so the"
echo "published trust anchor matches what the token signs with:"
echo ""
cat "$TMPDIR/root-signer.pem"

# ── Verify ──────────────────────────────────────────────────────────
echo ""
echo "Verifying token objects..."
pkcs11-tool --module "$PKCS11_MODULE" \
  --token-label "$TOKEN_LABEL" \
  --login --pin "$USER_PIN" \
  --list-objects

# ── Fix ownership ──────────────────────────────────────────────────
chown -R "$RUNNER_USER:$RUNNER_USER" "$TOKEN_DIR"

# ── Print summary ──────────────────────────────────────────────────
cat <<SUMMARY

════════════════════════════════════════════════════════
  SoftHSM2 token initialized successfully
════════════════════════════════════════════════════════

  Config file:      $CONF_PATH
  Token directory:  $TOKEN_DIR
  Token label:      $TOKEN_LABEL
  Key label:        $KEY_LABEL
  Cert label:       $CERT_LABEL
  Key ID:           $KEY_ID
  PKCS#11 module:   $PKCS11_MODULE
  Runner user:      $RUNNER_USER

  GitHub repo configuration needed:

    Variables (Settings → Variables → Actions):
      DEFAULT_SIGNING_MODE  = softhsm
      SOFTHSM_CONF_PATH    = $CONF_PATH
      SOFTHSM_TOKEN_LABEL  = $TOKEN_LABEL
      SOFTHSM_KEY_LABEL    = $KEY_LABEL
      SOFTHSM_CERT_LABEL   = $CERT_LABEL
      SOFTHSM_KEY_ID       = $KEY_ID

    Secrets (Settings → Secrets → Actions):
      SOFTHSM_PIN           = <the user PIN you just entered>

════════════════════════════════════════════════════════
SUMMARY
