#!/usr/bin/env bash
#
# Initialize a persistent SoftHSM2 token on a self-hosted GitHub Actions runner.
#
# Run this ONCE on the runner host before enabling signing_mode=softhsm.
# The token persists across workflow runs — the same key signs every build.
#
# Usage:
#   sudo ./setup-softhsm-runner.sh [options]
#
# Options:
#   --token-label NAME    Token label (default: trust-lists)
#   --key-label NAME      Signing key label (default: signing-key)
#   --cert-label NAME     Certificate label (default: signing-cert)
#   --key-id HEX          Key/cert ID in hex (default: 01)
#   --key-type TYPE       Key type for pkcs11-tool (default: ec:prime256v1)
#   --cert-subject SUB    Certificate subject (default: /CN=trust.siros.org Trust List Signer)
#   --cert-days N         Certificate validity in days (default: 1095 = 3 years)
#   --token-dir PATH      Token storage directory (default: /var/lib/softhsm/trust-lists)
#   --conf-path PATH      Config file path (default: /etc/softhsm/trust-lists.conf)
#   --runner-user USER    GitHub runner user (default: runner)
#
set -euo pipefail

# ── Defaults ────────────────────────────────────────────────────────
TOKEN_LABEL="trust-lists"
KEY_LABEL="signing-key"
CERT_LABEL="signing-cert"
KEY_ID="01"
KEY_TYPE="ec:prime256v1"
CERT_SUBJECT="/CN=trust.siros.org Trust List Signer"
CERT_DAYS=1095
TOKEN_DIR="/var/lib/softhsm/trust-lists"
CONF_PATH="/etc/softhsm/trust-lists.conf"
RUNNER_USER="runner"

# ── Parse args ──────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --token-label)  TOKEN_LABEL="$2"; shift 2 ;;
    --key-label)    KEY_LABEL="$2"; shift 2 ;;
    --cert-label)   CERT_LABEL="$2"; shift 2 ;;
    --key-id)       KEY_ID="$2"; shift 2 ;;
    --key-type)     KEY_TYPE="$2"; shift 2 ;;
    --cert-subject) CERT_SUBJECT="$2"; shift 2 ;;
    --cert-days)    CERT_DAYS="$2"; shift 2 ;;
    --token-dir)    TOKEN_DIR="$2"; shift 2 ;;
    --conf-path)    CONF_PATH="$2"; shift 2 ;;
    --runner-user)  RUNNER_USER="$2"; shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# ── Preflight checks ───────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root (sudo)." >&2
  exit 1
fi

for cmd in softhsm2-util pkcs11-tool openssl; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "Required command not found: $cmd" >&2
    echo "Install with: apt-get install softhsm2 opensc openssl" >&2
    exit 1
  fi
done

# Find PKCS#11 module
PKCS11_MODULE=""
for p in /usr/lib/softhsm/libsofthsm2.so /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so /usr/lib64/softhsm/libsofthsm2.so /usr/local/lib/softhsm/libsofthsm2.so; do
  if [ -f "$p" ]; then
    PKCS11_MODULE="$p"
    break
  fi
done
if [ -z "$PKCS11_MODULE" ]; then
  echo "Could not find libsofthsm2.so — is softhsm2 installed?" >&2
  exit 1
fi

# ── Create token directory ──────────────────────────────────────────
echo "Creating token directory: $TOKEN_DIR"
mkdir -p "$TOKEN_DIR"
chmod 750 "$TOKEN_DIR"
chown "$RUNNER_USER:$RUNNER_USER" "$TOKEN_DIR"

# ── Write SoftHSM2 config ──────────────────────────────────────────
echo "Writing SoftHSM2 config: $CONF_PATH"
mkdir -p "$(dirname "$CONF_PATH")"
cat > "$CONF_PATH" <<EOF
# SoftHSM2 configuration for trust-lists signing
# Generated by setup-softhsm-runner.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
directories.tokendir = $TOKEN_DIR
objectstore.backend = file
log.level = INFO
slots.removable = true
EOF
chmod 644 "$CONF_PATH"

# ── Initialize token ───────────────────────────────────────────────
echo "Initializing SoftHSM2 token..."
read -rsp "Enter user PIN for the token: " USER_PIN
echo
read -rsp "Enter SO (admin) PIN for the token: " SO_PIN
echo

export SOFTHSM2_CONF="$CONF_PATH"

softhsm2-util --init-token --free \
  --label "$TOKEN_LABEL" \
  --so-pin "$SO_PIN" \
  --pin "$USER_PIN"

# ── Generate signing key in token ──────────────────────────────────
echo "Generating signing key ($KEY_TYPE) in token..."
pkcs11-tool --module "$PKCS11_MODULE" \
  --token-label "$TOKEN_LABEL" \
  --login --pin "$USER_PIN" \
  --keypairgen --key-type "$KEY_TYPE" \
  --id "$KEY_ID" \
  --label "$KEY_LABEL"

# ── Generate and import certificate ─────────────────────────────────
echo "Generating self-signed certificate..."
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

# Determine openssl key args from KEY_TYPE
case "$KEY_TYPE" in
  ec:prime256v1) OPENSSL_KEY_ARGS="-newkey ec -pkeyopt ec_paramgen_curve:prime256v1" ;;
  ec:secp384r1)  OPENSSL_KEY_ARGS="-newkey ec -pkeyopt ec_paramgen_curve:secp384r1" ;;
  ec:secp521r1)  OPENSSL_KEY_ARGS="-newkey ec -pkeyopt ec_paramgen_curve:secp521r1" ;;
  rsa:*)         BITS="${KEY_TYPE#rsa:}"; OPENSSL_KEY_ARGS="-newkey rsa:$BITS" ;;
  *)             echo "Unsupported key type for cert generation: $KEY_TYPE" >&2; exit 1 ;;
esac

# shellcheck disable=SC2086
openssl req -new -x509 -nodes \
  $OPENSSL_KEY_ARGS \
  -keyout "$TMPDIR/temp-key.pem" \
  -out "$TMPDIR/cert.pem" \
  -days "$CERT_DAYS" \
  -subj "$CERT_SUBJECT"

pkcs11-tool --module "$PKCS11_MODULE" \
  --token-label "$TOKEN_LABEL" \
  --login --pin "$USER_PIN" \
  --write-object "$TMPDIR/cert.pem" --type cert \
  --id "$KEY_ID" \
  --label "$CERT_LABEL"

# ── Verify ──────────────────────────────────────────────────────────
echo ""
echo "Verifying token objects..."
pkcs11-tool --module "$PKCS11_MODULE" \
  --token-label "$TOKEN_LABEL" \
  --login --pin "$USER_PIN" \
  --list-objects

# ── Fix ownership ──────────────────────────────────────────────────
chown -R "$RUNNER_USER:$RUNNER_USER" "$TOKEN_DIR"

# ── Print summary ──────────────────────────────────────────────────
cat <<SUMMARY

════════════════════════════════════════════════════════
  SoftHSM2 token initialized successfully
════════════════════════════════════════════════════════

  Config file:      $CONF_PATH
  Token directory:  $TOKEN_DIR
  Token label:      $TOKEN_LABEL
  Key label:        $KEY_LABEL
  Cert label:       $CERT_LABEL
  Key ID:           $KEY_ID
  PKCS#11 module:   $PKCS11_MODULE
  Runner user:      $RUNNER_USER

  GitHub repo configuration needed:

    Variables (Settings → Variables → Actions):
      DEFAULT_SIGNING_MODE  = softhsm
      SOFTHSM_CONF_PATH    = $CONF_PATH
      SOFTHSM_TOKEN_LABEL  = $TOKEN_LABEL
      SOFTHSM_KEY_LABEL    = $KEY_LABEL
      SOFTHSM_CERT_LABEL   = $CERT_LABEL
      SOFTHSM_KEY_ID       = $KEY_ID

    Secrets (Settings → Secrets → Actions):
      SOFTHSM_PIN           = <the user PIN you just entered>

════════════════════════════════════════════════════════
SUMMARY
